export default `
  Last updated: May 15, 2020  
 
   І. The Policy:
  1. This Privacy Policy (“Privacy Policy”) regulates the collection, use, and disclose of Personal Data and other information when You use Trustee Wallet  (“Wallet”) and regulates legal relationship in the field of personal data protection between You and BLOCKSOFTLAB INC, File Number 7176888, registered in the USA, registered office in the State of Delaware is located at 300 Delaware Avenue, Suite 210-A, Wilmington, DE 19801 in New Castle County.
Unless otherwise defined in this Privacy Policy, terms used in this Privacy Policy have the same meanings as in our Terms of Use. 
  2. The Privacy Policy is part of  Terms of Use.
  3. If you do not agree with this Privacy Policy, please do not use the Wallet.    
  4. Please read the following terms carefully before you start using Trustee Wallet (can be called as the Wallet). Upon use of the Wallet, you certify that you consent to Privacy Policy and also accept  Terms of Use.  
  5. The Wallet is intended solely for use by a legal entity or full-aged individual (18 years). Use of the Wallet by non-adult is prohibited, we are not responsible for any consequences caused by the use of Wallet by non-adult.
  6. By providing us with Your personal information, You also consent for us to collect, hold, use and disclose your Personal Data in accordance with this Privacy Policy.  

   II. Definition: 
Personal Data means data about a living individual who can be identified from those data.
Usage Data is data collected automatically, either generated by the use of the Wallet or from the infrastructure itself (for example, the duration of a page visit).
Data Controller means person who determines the purposes for which and the manner in which any personal information are, or are to be, processed.
For the purpose of this Privacy Policy, we are a Data Controller of Your Personal Data.
If You have any questions, contact us by:  https://t.me/trustee_support_bot 
Data Subject (or You) is any living individual who is using our Wallet and is the subject of Personal Data.

   III. Legal grounds for the processing of Your Personal Data:
  1) consent to the processing of Personal Data received from You;
  2) processing is necessary for the performance of a contract with You stated in Terms of Use;
  3) processing is necessary for compliance with a legal obligation to which the Data controller is subject; 
  4) processing is in our legitimate interests and is not overridden by Your rights.

   IV. Types of information we collect:
  1. When you use the Wallet or/ and visit our Website, You may provide us with such types of information:
  A. Usage Data/ Cookies;
  B. Personal Data which we collect for the providing of a certain features of the Wallet.
  2. You must not register to use the Wallet.
  3. When You use the Wallet You do not need to provide us with Personal Data unless otherwise specified in this Privacy Policy.    

  А. Usage Data/ Cookies;
  1) With regard to each of Your visits to our Website or with our mobile application  we automatically may collect the Usage Data   - following information:
 - Information that Your browser sends whenever You use of the Wallet
 - Information about Your use of the Wallet, including the type of browser and version You use; 
 - The pages that You visit, the time and date of Your visit,  the time spent on those pages,  the last access time of Your Wallet; 
 - Information about the device you use including the hardware model, operating system and version, and unique device identifiers and other diagnostic data, but this information is anonymized and not tied to any particular person.
  2) Cookies. We use cookies and similar tracking technologies to track the activity on the Wallet and hold certain information.
You can easily remove any cookies that have been created in the cookie folder on Your browser setting. 
You can instruct Your browser to refuse all cookies or to indicate where a cookie is being sent.

  B. Personal Data which we collect for the providing of certain Feature of the Wallet: 
  1) To perform Transaction between Virtual assets and Fiat Money we collect following information about your bank details: 
 - bank card number;
 - expiration date.
  2)  We collect Personal Data by receiving the above information from You and use it purpose states in this Privacy Policy. 
  3) By submitting your bank details, you grant Use the right to share the  Personal Data/ information about your bank details with third parties/service providers for purposes of fulfillment of Transactions.
  4) We share Your Personal Data with third parties/service providers with which we have signed agreements to make sure that Your Personal Data is secured. 
  5) By submitting your Personal Data/ bank details, You agree that we do not bear any responsibility for the actions of such third parties/service providers, nor any actions of any other person, including actions related to the collection, processing, and transmission of such information. You agree that we are not liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses as a result of transferring by you to us Personal Data / information about your bank details. 
  6) If no transactions between Virtual assets and Fiat Money occur, the Personal Data/ the information about bank details are not collected. 
 
   V. Purposes of collecting Personal Data / bank details: 
  1) maintaining and providing You with  the Wallet;
  2) providing, maintaining, delivering or improving our Website, the Wallet provided through our  mobile application; 
  3) managing and developing our business and operations;
  4) making more of such services available to You where possible and appropriate;
  5) promotion of  the Wallet and other marketing purposes;
  6) ulfilling our legal or regulatory requirements;
  7) developing new products or services;
  8) protecting our rights and property;
  9) providing You with the information or services that You have requested;
  10) carrying out any actions for which we have received Your consent, carrying out any other purpose or reason for which the information was collected.

   VI. Disclosure of  Personal Data/ bank details:
  1. We will only disclose Personal Data/ information about Your bank details in the following ways:  
  1) with Your consent or at Your instructions;
  2) with third parties that perform work for us for providing You with certain features of the Wallet;
  3) certain information You may choose to share may be displayed publicly;
  4) in response to a request for information if we believe disclosure is in accordance with or required by, any applicable law, regulation or legal process.
  2. We collect, use,  process, disclose and transfer your Personal Data /information about your bank details only in purpose to perform Transaction between Virtual assets and Fiat Money.  
  3. Terms associated with the collection, using, processing, disclosing, transferring  Personal Data and information about your bank details to a third party, liability, etc., are set out in section B of  Chapter IV  this Privacy Policy. 

   VII. Security of Personal Data / bank details:
  1. We protect Personal Data / bank details with appropriate physical, technological and organizational safeguards and security measures. 
  2. The access to Personal data is restricted and certain access rights are set.

   VIII.  Storage / Retention of Your Personal Data / bank details:
  1. We store your Personal Data/ bank details within Application in an encoded format. 
  2. We do not store your Personal Data/ information about bank details on servers. 
  3. We confirm that any third-party with whom we share Your Personal Data will provide the same or equal protection of user data as stated in this Privacy Policy and required by law. 
  4. We retain the information of You only as long as it is necessary, in accordance with the purpose of collecting the data and required by law. When Personal Data and other information are no longer needed we have procedures either to destroy, delete, erase or convert it to an anonymous form.
  5. All Personal Data can be removed by You if You chose to. You can revoke consent and/or request deletion of Your Personal Data at any time contacting us at https://t.me/trustee_support_bot .  
  6. We reserve the right to store/process personal data in accordance with the specific purpose of their storage/processing without limitation of storage and processing time in cases stipulated by law.
  7. Withdrawal of consent and/or deletion of Your Personal Data disables the use of certain Feature of the Wallet by You. 

   IX. Data subject’s rights:
  1. You have the right to:
  a) modify and correct your Personal Data at any time and you are therefore responsible for the accuracy of Your Personal Data;
  b) ask about Your Personal Data from us to data portability and also the right to request us to restrict the processing of Your Personal Data and/or to delete it in case obligation to retain the data is not set out by the law; 
  c) object to processing of Your Personal Data and/or to withdraw consent at any time, without affecting the lawfulness of processing based on consent before its withdrawal;
  2. Legal Basis for Processing Personal Data in the European Economic Area (EEA) stated in the General Data Protection Regulation (GDPR). We aim to take reasonable steps to allow You to correct, amend, delete, or limit the use of Your Personal Data. 
If You are a resident of the European Economic Area (EEA), You have certain data protection rights stated in the General Data Protection Regulation:
The right to access, update or to delete the information we have on You. Whenever made possible, You can access, update or request the deletion of Your Personal Data directly. If You are unable to perform these actions yourself, please contact us to assist You.
The right of rectification. You have the right to have Your information rectified if that information is inaccurate or incomplete.
The right to object. You have the right to object to our processing of Your Personal Data.
The right of restriction. You have the right to request that we restrict the processing of Your personal information.
The right to withdraw consent. You also have the right to withdraw Your consent at any time where we relied on Your consent to process Your personal information.
  3. You can exercise your rights by contacting us at https://t.me/trustee_support_bot . 
If You wish to be informed what Personal Data we hold about You and if You want it to be removed from our systems, please contact us athttps://t.me/trustee_support_bot  
  4. You have the right to complain to a Data Protection Authority about our collection and use of Your Personal Data. For more information, please contact Your local data protection authority in the European Economic Area (EEA).

   X. Children's Privacy:
  1. Wallet does not address anyone under the age of 18 ("Children").
  2. We do not knowingly collect personally identifiable information from anyone under the age of 18. If You are a parent or guardian and You are aware that your Children has provided us with Personal Data, please contact us at https://t.me/trustee_support_bot 
  3. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information.

   XI. Amendments:
  1. We may change, amend, delete or add this Privacy Policy at any time. 
  2. Any such changes will be effective upon the posting on a Website or mobile application. The effective date which is at the top of the Privacy Policy informs You about the latest version of Privacy Policy. 
  3. Your continued use of the Wallet and/or Website constitutes Your acceptance of such changes and Your consent to the processing of Personal Data according to the latest version. If You do not agree with any such changes, do not continue to use the Wallet and/or  Website.

   XII. Questions and Complaints:
  1. Any questions about this Policy, the collection, use, and disclosure of Personal Data or access to Your Personal Data which is required by law (or would be so subject had the storage in question taken place in a relevant EU member state if the case may be but not otherwise) to be disclosed should be directed to https://t.me/trustee_support_bot 
  2. In the event that You wish to make a complaint about how we process your personal data, please contact us in the first instance at  https://t.me/trustee_support_bot  and we will endeavor to deal with your request as soon as possible. 


`
