# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TrusteeWallet' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TrusteeWallet
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/DynamicLinks'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNAwesomeCardIO', :path => '../node_modules/react-native-awesome-card-io'

  pod 'RNShare', :path => '../node_modules/react-native-share'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'Flurry-iOS-SDK/FlurrySDK'
  pod 'Flurry-iOS-SDK/FlurryAds'

  # pod 'React', :path => '../node_modules/react-native'
  # pod 'React', :path => '../node_modules/react-native', subspecs: [
    # 'Core',
    # 'CxxBridge',
    # 'DevSupport',
    # 'RCTText',
    # 'RCTNetwork',
    # 'RCTWebSocket',
    # 'RCTAnimation',
    # 'RCTActionSheet',
    # 'RCTBlob',
    # 'RCTCameraRoll',
    # 'RCTGeolocation',
    # 'RCTImage'
    # 'RCTPushNotification',
    # 'RCTSettings',
    # 'RCTTest',
    # 'RCTVibration',
    # 'RCTLinkingIOS'
  # ]

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'lottie-react-native', :podspec => '../node_modules/lottie-react-native/lottie-react-native.podspec'

  pod 'RNKeychain', :path => '../node_modules/react-native-keychain'

  pod 'TouchID', :path => '../node_modules/react-native-touch-id'

  pod 'RNLocalize', :path => '../node_modules/react-native-localize'

  pod 'react-native-background-timer', :path => '../node_modules/react-native-background-timer'

  pod 'react-native-blur', :path => '../node_modules/@react-native-community/blur'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  target 'TrusteeWallet-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

    pod 'RNAwesomeCardIO', :path => '../node_modules/react-native-awesome-card-io'

    pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

    pod 'React', :path => '../node_modules/react-native'

    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

    pod 'Folly', :podspec => "../node_modules/react-native/third-party-podspecs/Folly.podspec"

  end

  # target 'TrusteeWalletTests' do
   #  inherit! :search_paths
    # Pods for testing
  # end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end

      if target.name == "yoga"
        target.remove_from_project
      end
    end
  end

end
