module.exports = {
    TTnSHzUoho1CU6zFYVzVSCKq8EX8ZddkVv: 'JUSTSWAP-WTRX-TRX',
    TJmTeYk5zmg8pNPGYbDb2psadwVLYDDYDr: 'JUSTSWAP-DICE-TRX',
    TQn9Y2khEsLJW1ChVWFMSMeRDow5KcbLSE: 'JUSTSWAP-USDT-TRX',
    TQcia2H2TU3WrFk9sKtdK9qCfkW8XirfPQ: 'JUSTSWAP-USDJ-TRX',
    TLLBBiX3HqVZZsUQTBXgurA3pdw317PmjM: 'JUSTSWAP-HT-TRX',
    TYN6Wh11maRfzgG7n5B6nM5VW1jfGs9chu: 'JUSTSWAP-WIN-TRX',
    TUEYcyPAqc4hTg1fSuBCPc18vGWcJDECVw: 'JUSTSWAP-SUN-TRX',
    TKAtLoCB529zusLfLVkGvLNis6okwjB7jf: 'JUSTSWAP-BTC-TRX',
    TYukBQZ2XXCcRCReAUguyXncCWNY9CEiDQ: 'JUSTSWAP-JST-TRX',
    TH2mEwTKNgtg8psR6Qx2RBUXZ48Lon1ygu: 'JUSTSWAP-WBTT-TRX'
}
