/**
 * @author Ksu
 * @version 0.20
 */
export namespace BlocksoftDictTypes {

    export enum Code {
        BTC = 'BTC',
        BTC_SEGWIT = 'BTC_SEGWIT',
        BTC_SEGWIT_COMPATIBLE = 'BTC_SEGWIT_COMPATIBLE',
        ETH_ERC_20 = 'ETH_ERC_20',
        USDT = 'USDT',
        LTC = 'LTC',
        ETH = 'ETH',
        ETH_USDT = 'ETH_USDT',
        ETH_UAX = 'ETH_UAX',
        ETH_TRUE_USD = 'ETH_TRUE_USD',
        ETH_BNB = 'ETH_BNB',
        ETH_USDC = 'ETH_USDC',
        ETH_PAX = 'ETH_PAX',
        ETH_DAI = 'ETH_DAI',
        ETH_DAIM = 'ETH_DAIM',
        TRX = 'TRX',
        XMR = 'XMR',
        XLM = 'XLM',
        BTC_TEST = 'BTC_TEST',
        BCH = 'BCH',
        BSV = 'BSV',
        BTG = 'BTG',
        DOGE = 'DOGE',
        XVG = 'XVG',
        XRP = 'XRP',
        ETH_ROPSTEN = 'ETH_ROPSTEN',
        ETH_RINKEBY = 'ETH_RINKEBY',
        TRX_USDT = 'TRX_USDT',
        TRX_BTT = 'TRX_BTT',
        ETH_OKB = 'ETH_OKB',
        ETH_MKR = 'ETH_MKR',
        ETH_KNC = 'ETH_KNC',
        ETH_COMP = 'ETH_COMP',
        ETH_BAL = 'ETH_BAL',
        ETH_LEND = 'ETH_LEND',
        ETH_BNT = 'ETH_BNT',
        ETH_SOUL = 'ETH_SOUL',
        ETH_ONE = 'ETH_ONE',
        FIO = 'FIO',
        BNB = 'BNB',
        BNB_SMART = 'BNB_SMART',
        BNB_SMART_20 = 'BNB_SMART_20',
        ETC = 'ETC',
        VET = 'VET',
        SOL = 'SOL',
        WAVES = 'WAVES',
        ASH = 'ASH'
    }
}
